name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: One line describing the capability you want.
      placeholder: "Support for streaming transcription with partial results."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What pain point or limitation does this address?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like it to work? Be specific about behavior or API.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you thought about and why they fall short.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Examples, prior art, or anything else relevant.
    validations:
      required: false
